const gallery2023 = [
  '/foro-nearshoring/gallery/foro_nearshoring_1.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_2.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_3.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_4.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_5.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_6.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_7.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_8.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_9.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_10.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_11.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_12.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_13.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_14.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_15.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_16.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_17.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_18.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_19.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_20.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_21.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_22.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_23.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_24.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_25.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_26.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_27.webp',
  '/foro-nearshoring/gallery/foro_nearshoring_28.webp'
]

export { gallery2023 }
