const programITM = {
    stage_1: {
      speakers: [
        {
          id: 0,
          hour: '13:30 hrs',
          duration: '45 min',
          event: 'Inauguración y bienvenida',
          name: 'Bernd Rohde |  Wolfgang Dold | Luigi De Chia',
          avatar: '',
          avatar2: '/foro-nearshoring/speakers/BerndRohde.webp',
          avatar3: '/foro-nearshoring/speakers/WolfgangDold.webp',
          avatar4: '/foro-nearshoring/speakers/LuigiChia.webp',
          rol: 'CEO Italian German Exhibition Company Mexico | Embajador de Alemania | Embajador de Italia ',
        },
        {
          id: 0,
          hour: '14:00 hrs',
          duration: '45 min',
          event: 'Foro Embajadores, una visión global del Nearshoring',
          name: 'Gautier Mignot |  Wolfgang Dold | Luigi De Chia',
          avatar: '',
          avatar2: '/foro-nearshoring/speakers/GautierMignot.webp',
          avatar3: '/foro-nearshoring/speakers/WolfgangDold.webp',
          avatar4: '/foro-nearshoring/speakers/LuigiChia.webp',
          rol: ' CEO Italian German Exhibition Company | Embajador de Alemania | Embajador de Italia ',
        },
        {
          id: 0,
          id_s2: 0,
          hour: '15:00 hrs',
          duration: '45 min',
          event: 'Casos de éxito que han aprovechado el Nearshoring',
          name: 'Ramón Alfaro | Luz María de la Mora |  Jorge Peydro Aznar |  Carlos Talamantes',
          avatar: '/foro-nearshoring/speakers/RamonAlfaro.webp',
          avatar2: '/foro-nearshoring/speakers/LuzMora.webp',
          avatar3: '/foro-nearshoring/speakers/JorgeAznar.webp',
          avatar4: '/foro-nearshoring/speakers/CarlosTalamantes.webp',
          rol: 'Secretario de Desarrollo Económico Sustentable | Ex-subsecretaria de Comercio Exterior | Ministro Consejero de la Unión Europea en México | CEO Witzenmann',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '16:00 hrs',
          duration: '45 min',
          event: 'Tendencias del nearshoring hacia la segunda mitad de la década',
          name: 'Luis Ernesto Rojas Ávila | Esaú Garza |  Marco Villarreal |  Ari-Ben Saks | Selene Diez Reyes',
          avatar: '/foro-nearshoring/speakers/LuisErnestoRojas.webp',
          avatar2: '/foro-nearshoring/speakers/EsauGarza.webp',
          avatar3: '/foro-nearshoring/speakers/AriBen.webp',
          avatar4: '/foro-nearshoring/speakers/SeleneDiezReyes.webp',
          rol: 'Director General COFOCE | CEO ASMS | CEO HISUN Motor México | Ernst & Young Global Specialist | CEO & Founder de Forte Innovation Consulting',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '17:00 hrs',
          duration: '45 min',
          event: 'Los elementos fundamentales para el éxito del Nearshoring',
          name: 'Claudia Esteves | José Zozaya |  Armando Cortés |  Luis Lozano',
          avatar: '/foro-nearshoring/speakers/ClaudiaEsteves.webp',
          avatar2: '/foro-nearshoring/speakers/JoseGuillermo.webp',
          avatar3: '/foro-nearshoring/speakers/ArmandoCortes.webp',
          avatar4: '/foro-nearshoring/speakers/LuisLozano.webp',
          rol: 'Presidenta AMPIP | Presidente AMIA | Director General INA | Presidente Toyota Motor México',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '18:00 hrs',
          duration: '45 min',
          event: '  ',
          name: 'Bernd Rohde | Azul Ogazón',
          avatar: '/foro-nearshoring/speakers/BerndRohde.webp',
          avatar2: '/foro-nearshoring/speakers/AzulOgazon.webp',
          avatar3: '',
          avatar4: '',
          rol: ' CEO Italian German Exhibition Company Mexico | Directora de Industrial Transformation Mexico ',
        },
      ]
    }
  }
  export { programITM }