const programITM = {
    stage_1: {
      speakers: [
        {
          id: 0,
          hour: '13:30 hrs',
          duration: '45 min',
          event: 'Inauguración y bienvenida',
          name: 'Bernd Rohde',
          avatar: '/foro-nearshoring/speakers/BerndRohde.webp',
          avatar2: '',
          avatar3: '',
          avatar4: '',          
          rol: 'CEO Italian German Exhibition Company Mexico | Embajador de Alemania en México| Embajador de Italia en México',
        },
        {
          id: 0,
          hour: '14:00 hrs',
          duration: '45 min',
          event: 'Foro Embajadores, una visión global del Nearshoring',
          name: '',
          avatar: '',
          avatar2: '',
          avatar3: '',
          avatar4: '',                  
          rol: ' Embajador de la Unión Europa en México | Embajador de Alemania en México | Embajador de Italia en México',
        },
        {
          id: 0,
          id_s2: 0,
          hour: '15:00 hrs',
          duration: '45 min',
          event: 'Casos de éxito que han aprovechado el Nearshoring',
          name: 'Luz María de la Mora',
          avatar: '/foro-nearshoring/speakers/LuzMora.webp',
          avatar2: '',
          avatar3: '',
          avatar4: '',          
          rol: 'Secretario de Desarrollo Económico Sustentable de Guanajuato | Ex-subsecretaria de Comercio Exterior | Ministro Consejero de la Unión Europea en México | CEO Witzenmann',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '16:00 hrs',
          duration: '45 min',
          event: 'Tendencias del nearshoring hacia la segunda mitad de la década',
          name: 'Luis Ernesto Rojas Ávila | Esaú Garza |  Marco Villarreal |  Ari-Ben Saks | Selene Diez Reyes',
          avatar: '/foro-nearshoring/speakers/LuisErnestoRojas.webp',
          avatar2: '/foro-nearshoring/speakers/EsauGarza.webp',
          avatar3: '/foro-nearshoring/speakers/AriBen.webp',
          avatar4: '/foro-nearshoring/speakers/SeleneDiezReyes.webp',
          rol: 'Director General COFOCE | CEO ASMS | CEO HISUN Motor México | Ernst & Young Global Specialist | CEO & Founder de Forte Innovation Consulting',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '17:00 hrs',
          duration: '45 min',
          event: 'Los elementos fundamentales para el éxito del Nearshoring',
          name: 'Claudia Esteves | José Zozaya |  Armando Cortés ',
          avatar: '/foro-nearshoring/speakers/ClaudiaEsteves.webp',
          avatar2: '/foro-nearshoring/speakers/JoseGuillermo.webp',
          avatar3: '/foro-nearshoring/speakers/ArmandoCortes.webp',
          avatar4: '',          
          rol: 'Presidenta AMPIP | Presidente AMIA | Director General INA | Presidente Toyota Motor México',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '18:00 hrs',
          duration: '45 min',
          event: '  ',
          name: 'Bernd Rohde | Azul Ogazón',
          avatar: '/foro-nearshoring/speakers/BerndRohde.webp',
          avatar2: '/foro-nearshoring/speakers/AzulOgazon.webp',
          avatar3: '',
          avatar4: '',
          rol: ' CEO Italian German Exhibition Company Mexico | Directora de Industrial Transformation Mexico ',
        },
      ]
    }
  }
  export { programITM }