const programITM = {
    stage_1: {
      speakers: [
        {
          id: 0,
          hour: '13:30 hrs',
          duration: '45 min',
          event: 'Inauguración del Foro y palabras de Bienvenida',
          name: 'Diego Sinhue Rodríguez Vallejo | Bernd Rohde |  Wolfgang Dold | Luigi De Chia',
          avatar: '/foro-nearshoring/speakers/DiegoSinhue.webp',
          avatar2: '/foro-nearshoring/speakers/BerndRohde.webp',
          avatar3: '/foro-nearshoring/speakers/WolfgangDold.webp',
          avatar4: '/foro-nearshoring/speakers/LuigiChia.webp',
          rol: 'Gobernador Constitucional de Guanajuato | CEO Italian German Exhibition Company | Embajador de Alemania | Embajador de Italia ',
        },
        {
          id: 0,
          hour: '14:00 hrs',
          duration: '45 min',
          event: 'Foro Embajadores, una visión global del Nearshoring',
          name: 'Diego Sinhue Rodríguez Vallejo | Gautier Mignot |  Wolfgang Dold | Luigi De Chia',
          avatar: '/foro-nearshoring/speakers/DiegoSinhue.webp',
          avatar2: '/foro-nearshoring/speakers/GautierMignot.webp',
          avatar3: '/foro-nearshoring/speakers/WolfgangDold.webp',
          avatar4: '/foro-nearshoring/speakers/LuigiChia.webp',
          rol: 'Gobernador Constitucional de Guanajuato | CEO Italian German Exhibition Company | Embajador de Alemania | Embajador de Italia ',
        },
        {
          id: 0,
          id_s2: 0,
          hour: '15:00 hrs',
          duration: '45 min',
          event: 'Casos de éxito que han aprovechado el Nearshoring',
          name: 'Ramón Alfaro | Luz María de la Mora |  Jorge Peydro Aznar |  Carlos Talamantes',
          avatar: '',
          avatar2: '',
          avatar3: '',
          avatar4: '',
          rol: 'Secretario de Desarrollo Económico Sustentable | Ex subsecretaria de comercio exterior | Ministro Consejero UE en México | CEO Witzenmann ',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '16:00 hrs',
          duration: '45 min',
          event: 'Tendencias del nearshoring hacia la segunda mitad de la decada',
          name: 'Luis Ernesto Rojas Ávila | Esaú Garza |  Marco Villarreal |  Ari-Ben Saks',
          avatar: '',
          avatar2: '',
          avatar3: '',
          avatar4: '',
          rol: 'Director General COFOCE | CEO ASMS | CEO HISUN Motor México | Ernst & Young Global Specialist ',
        },
        {
          id: 1,
          id_s2: 0,
          hour: '17:00 hrs',
          duration: '45 min',
          event: 'Palabras de cierre y conclusiones del Foro',
          name: 'Bernd Rohde | Azul Ogazón',
          avatar: '/foro-nearshoring/speakers/BerndRohde.webp',
          avatar2: '',
          avatar3: '',
          avatar4: '',
          rol: ' CEO IGECo | Directora ITM ',
        },
      ]
    }
  }
  export { programITM }